name: Release
on:
  push:
    branches:
      - 'main'

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  draft_release:
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.SECRET }}
        run: npx --no-install electron-builder --config .electron-builder.config.js

      - name: Remove unpacked directories
        run: |
          rm -rf dist/linux-unpacked
          rm -rf dist/win-unpacked
          rm -rf dist/mac

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: dist/